# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    hostname: ca_peerOrg1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6c7eb5f82840048bde19c5de0bc0245d4a4f9af31e151cd5fa55c9753c09e7de_sk
    ports:
      - "7054:7054"
    volumes:
      - ./kafka/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6c7eb5f82840048bde19c5de0bc0245d4a4f9af31e151cd5fa55c9753c09e7de_sk -b admin:adminpw -d'
    container_name: ca_peerOrg1

  ca1:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    hostname: ca.org2.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6a201fa0c148f40269afb2f349ee9d92ef026036c1e4bbbd37e55f637236eed5_sk
    ports:
      - "8054:7054"
    volumes:
      - ./kafka/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6a201fa0c148f40269afb2f349ee9d92ef026036c1e4bbbd37e55f637236eed5_sk -b admin:adminpw -d'
    container_name: ca_peerOrg2

  ca2:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    hostname: ca.org3.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1c55b4fe1cea7d6d8af726a43432e7b56b5acacf1cf1c08fe1b02fffe345aead_sk
    ports:
      - "9054:7054"
    volumes:
      - ./kafka/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1c55b4fe1cea7d6d8af726a43432e7b56b5acacf1cf1c08fe1b02fffe345aead_sk -b admin:adminpw -d'
    container_name: ca_peerOrg3

  ca3:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    hostname: ca.org4.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bd67962a3903c3296223d4ecd8e9c8a41e60a28962d187cf7cff6c8932aefbf5_sk
    ports:
      - "10054:7054"
    volumes:
      - ./kafka/crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bd67962a3903c3296223d4ecd8e9c8a41e60a28962d187cf7cff6c8932aefbf5_sk -b admin:adminpw -d'
    container_name: ca_peerOrg4
