version: '2'

services:

  zookeeper-base:
    image: hyperledger/fabric-zookeeper:x86_64-1.0.5
    restart: always
    tty: true
    expose:
      - '2181'
      - '2888'
      - '3888'

  kafka-base:
    image: hyperledger/fabric-kafka:x86_64-1.0.5
    restart: always
    tty: true
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    expose:
      - '9092'